apiVersion: v1
kind: Pod
metadata:
  name: prometheus-metrics-generator
  namespace: victoria-metrics
  labels:
    app: prometheus-metrics-generator
    component: metrics-generator
spec:
  containers:
  - name: metrics-generator
    image: thabiger/prometheus-metrics-generator:latest
    ports:
    - name: web
      containerPort: 8001
      protocol: TCP
    - name: metrics
      containerPort: 9100
      protocol: TCP
    env:
    - name: PROMETHEUS_PORT
      value: "9100"
    - name: WEB_PORT
      value: "8001"
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    livenessProbe:
      httpGet:
        path: /
        port: web
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /metrics
        port: metrics
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: operator.victoriametrics.com/v1
kind: VMServiceScrape
metadata:
  name: prometheus-metrics-generator
  namespace: victoria-metrics
spec:
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    relabelConfigs:
    - action: replace
      sourceLabels: [__address__]
      targetLabel: instance
      regex: "(.*):.*"
      replacement: "${1}"
  selector:
    matchLabels:
      app: prometheus-metrics-generator
