apiVersion: v1
kind: Pod
metadata:
  name: stress-ng-pod
spec:
  containers:
  - name: stress-test
    image: alexeiled/stress-ng:latest
    args: ["--cpu", "4", "--io", "2", "--vm", "1", "--vm-bytes", "2G", "--timeout", "60s", "--metrics-brief"]
    resources:
      requests:
        memory: "1.2Gi"
        cpu: "500m"
      limits:
        memory: "1.5Gi"
        cpu: "2"
  restartPolicy: Never
