---
# Source: victoria-logs-cluster/charts/vector/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vlc-vector
  namespace: victorialogs
  labels:
    helm.sh/chart: vector-0.40.0
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/component: Agent
    app.kubernetes.io/version: "0.44.0-distroless-libc"
    app.kubernetes.io/managed-by: Helm
    
automountServiceAccountToken: true
---
# Source: victoria-logs-cluster/templates/vector-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-vl-config
  labels: 
    app: vlinsert
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-logs-cluster
    app.kubernetes.io/version: v1.36.1
    helm.sh/chart: victoria-logs-cluster-0.0.17
  namespace: victorialogs
data:
  vlc-victoria-logs-cluster-vector.yaml: |
    api:
      address: 0.0.0.0:8686
      enabled: false
      playground: true
    data_dir: /vector-data-dir
    sinks:
      exporter:
        address: 0.0.0.0:9090
        inputs:
        - internal_metrics
        type: prometheus_exporter
      vlogs:
        api_version: v8
        compression: gzip
        endpoints:
        - http://vlc-victoria-logs-cluster-vlinsert.victorialogs.svc.cluster.local.:9481/insert/elasticsearch
        healthcheck:
          enabled: false
        inputs:
        - parser
        mode: bulk
        request:
          headers:
            AccountID: "0"
            ProjectID: "0"
            VL-Msg-Field: message,msg,_msg,log.msg,log.message,log
            VL-Stream-Fields: stream,kubernetes.pod_name,kubernetes.container_name,kubernetes.pod_namespace
            VL-Time-Field: timestamp
        type: elasticsearch
    sources:
      internal_metrics:
        type: internal_metrics
      k8s:
        type: kubernetes_logs
    transforms:
      parser:
        inputs:
        - k8s
        source: |
          .log = parse_json(.message) ?? .message
          del(.message)
        type: remap
---
# Source: victoria-logs-cluster/charts/vector/templates/rbac.yaml
# Permissions to use Kubernetes API.
# Requires that RBAC authorization is enabled.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vlc-vector
  labels:
    helm.sh/chart: vector-0.40.0
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/component: Agent
    app.kubernetes.io/version: "0.44.0-distroless-libc"
    app.kubernetes.io/managed-by: Helm
    
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
      - pods
    verbs:
      - list
      - watch
---
# Source: victoria-logs-cluster/charts/vector/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vlc-vector
  labels:
    helm.sh/chart: vector-0.40.0
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/component: Agent
    app.kubernetes.io/version: "0.44.0-distroless-libc"
    app.kubernetes.io/managed-by: Helm
    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vlc-vector
subjects:
  - kind: ServiceAccount
    name: vlc-vector
    namespace: victorialogs
---
# Source: victoria-logs-cluster/charts/vector/templates/service-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: vlc-vector-headless
  namespace: victorialogs
  labels:
    helm.sh/chart: vector-0.40.0
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/component: Agent
    app.kubernetes.io/version: "0.44.0-distroless-libc"
    app.kubernetes.io/managed-by: Helm
    
  annotations:
spec:
  clusterIP: None
  ports:
    []
  selector:
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/component: Agent
  type: ClusterIP
---
# Source: victoria-logs-cluster/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels: 
    app: vlinsert
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-logs-cluster
    app.kubernetes.io/version: v1.36.1
    helm.sh/chart: victoria-logs-cluster-0.0.17
  name: vlc-victoria-logs-cluster-vlinsert
  namespace: victorialogs
spec:
  type: ClusterIP
  ports: 
    - name: http
      port: 9481
      protocol: TCP
      targetPort: http
  selector: 
    app: vlinsert
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/name: victoria-logs-cluster
---
# Source: victoria-logs-cluster/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels: 
    app: vlselect
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-logs-cluster
    app.kubernetes.io/version: v1.36.1
    helm.sh/chart: victoria-logs-cluster-0.0.17
  name: vlc-victoria-logs-cluster-vlselect
  namespace: victorialogs
spec:
  type: ClusterIP
  ports: 
    - name: http
      port: 9471
      protocol: TCP
      targetPort: http
  selector: 
    app: vlselect
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/name: victoria-logs-cluster
---
# Source: victoria-logs-cluster/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels: 
    app: vlstorage
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-logs-cluster
    app.kubernetes.io/version: v1.36.1
    helm.sh/chart: victoria-logs-cluster-0.0.17
  name: vlc-victoria-logs-cluster-vlstorage
  namespace: victorialogs
spec:
  type: ClusterIP
  clusterIP: None
  ports: 
    - port: 9491
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    app: vlstorage
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/name: victoria-logs-cluster
---
# Source: victoria-logs-cluster/charts/vector/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vlc-vector
  namespace: victorialogs
  labels:
    helm.sh/chart: vector-0.40.0
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/component: Agent
    app.kubernetes.io/version: "0.44.0-distroless-libc"
    app.kubernetes.io/managed-by: Helm
    
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vector
      app.kubernetes.io/instance: vlc
      app.kubernetes.io/component: Agent
  minReadySeconds: 0
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: vector
        app.kubernetes.io/instance: vlc
        app.kubernetes.io/component: Agent
        vector.dev/exclude: "true"
    spec:
      serviceAccountName: vlc-vector
      dnsPolicy: ClusterFirst
      containers:
        - name: vector
          image: "timberio/vector:0.44.0-distroless-libc"
          imagePullPolicy: IfNotPresent
          args:
            - -w
            - --config-dir
            - /etc/vector/
          env:
            - name: VECTOR_LOG
              value: "info"
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VECTOR_SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PROCFS_ROOT
              value: "/host/proc"
            - name: SYSFS_ROOT
              value: "/host/sys"
          ports:
            - containerPort: 9090
              name: prom-exporter
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: "/vector-data-dir"
            - name: config
              mountPath: "/etc/vector/"
              readOnly: true
            - mountPath: /var/log/
              name: var-log
              readOnly: true
            - mountPath: /var/lib
              name: var-lib
              readOnly: true
            - mountPath: /host/proc
              name: procfs
              readOnly: true
            - mountPath: /host/sys
              name: sysfs
              readOnly: true
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: vector-vl-config
        - name: data
          hostPath:
            path: "/var/lib/vector"
        - hostPath:
            path: /var/log/
          name: var-log
        - hostPath:
            path: /var/lib/
          name: var-lib
        - hostPath:
            path: /proc
          name: procfs
        - hostPath:
            path: /sys
          name: sysfs
---
# Source: victoria-logs-cluster/templates/vlinsert-server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: vlinsert
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-logs-cluster
    app.kubernetes.io/version: v1.36.1
    helm.sh/chart: victoria-logs-cluster-0.0.17
  name: vlc-victoria-logs-cluster-vlinsert
  namespace: victorialogs
spec:
  selector:
    matchLabels: 
      app: vlinsert
      app.kubernetes.io/instance: vlc
      app.kubernetes.io/name: victoria-logs-cluster
  replicas: 2
  template:
    metadata:
      labels: 
        app: vlinsert
        app.kubernetes.io/instance: vlc
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: victoria-logs-cluster
    spec:
      containers:
        - name: vlinsert
          image: victoriametrics/victoria-logs:v1.36.1
          imagePullPolicy: IfNotPresent
          securityContext: 
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          args: 
            - --envflag.enable
            - --http.shutdownDelay=15s
            - --httpListenAddr=:9481
            - --loggerFormat=json
            - --storageNode=vlc-victoria-logs-cluster-vlstorage-0.vlc-victoria-logs-cluster-vlstorage.victorialogs.svc.cluster.local.:9491
            - --storageNode=vlc-victoria-logs-cluster-vlstorage-1.vlc-victoria-logs-cluster-vlstorage.victorialogs.svc.cluster.local.:9491
          ports:
            - name: http
              containerPort: 9481
          readinessProbe: 
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe: 
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 15
            tcpSocket:
              port: http
            timeoutSeconds: 5
      securityContext: 
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
---
# Source: victoria-logs-cluster/templates/vlselect-server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: vlselect
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-logs-cluster
    app.kubernetes.io/version: v1.36.1
    helm.sh/chart: victoria-logs-cluster-0.0.17
  name: vlc-victoria-logs-cluster-vlselect
  namespace: victorialogs
spec:
  selector:
    matchLabels: 
      app: vlselect
      app.kubernetes.io/instance: vlc
      app.kubernetes.io/name: victoria-logs-cluster
  replicas: 2
  template:
    metadata:
      labels: 
        app: vlselect
        app.kubernetes.io/instance: vlc
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: victoria-logs-cluster
    spec:
      containers:
        - name: vlselect
          image: victoriametrics/victoria-logs:v1.36.1
          imagePullPolicy: IfNotPresent
          securityContext: 
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          args: 
            - --envflag.enable
            - --http.shutdownDelay=15s
            - --httpListenAddr=:9471
            - --loggerFormat=json
            - --storageNode=vlc-victoria-logs-cluster-vlstorage-0.vlc-victoria-logs-cluster-vlstorage.victorialogs.svc.cluster.local.:9491
            - --storageNode=vlc-victoria-logs-cluster-vlstorage-1.vlc-victoria-logs-cluster-vlstorage.victorialogs.svc.cluster.local.:9491
          ports:
            - name: http
              containerPort: 9471
          readinessProbe: 
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe: 
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 15
            tcpSocket:
              port: http
            timeoutSeconds: 5
      securityContext: 
        fsGroup: 1000
      terminationGracePeriodSeconds: 60
---
# Source: victoria-logs-cluster/templates/vlstorage-server.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels: 
    app: vlstorage
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-logs-cluster
    app.kubernetes.io/version: v1.36.1
    helm.sh/chart: victoria-logs-cluster-0.0.17
  name: vlc-victoria-logs-cluster-vlstorage
  namespace: victorialogs
spec:
  serviceName: vlc-victoria-logs-cluster-vlstorage
  selector:
    matchLabels: 
      app: vlstorage
      app.kubernetes.io/instance: vlc
      app.kubernetes.io/name: victoria-logs-cluster
  replicas: 2
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels: 
        app: vlstorage
        app.kubernetes.io/instance: vlc
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: victoria-logs-cluster
    spec:
      containers:
        - name: vlstorage
          image: victoriametrics/victoria-logs:v1.36.1
          imagePullPolicy: IfNotPresent
          securityContext: 
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          args: 
            - --envflag.enable
            - --http.shutdownDelay=15s
            - --httpListenAddr=:9491
            - --loggerFormat=json
            - --retentionPeriod=7d
            - --storageDataPath=/storage
          ports:
            - name: http
              containerPort: 9491
          readinessProbe: 
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: vlstorage-volume
              mountPath: /storage
      securityContext: 
        fsGroup: 1000
      terminationGracePeriodSeconds: 60
  minReadySeconds: 5
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: vlstorage-volume
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
# Source: victoria-logs-cluster/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels: 
    app: vlselect
    app.kubernetes.io/instance: vlc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-logs-cluster
    app.kubernetes.io/version: v1.36.1
    helm.sh/chart: victoria-logs-cluster-0.0.17
  name: vlc-victoria-logs-cluster-vlselect
  namespace: victorialogs
spec:
  ingressClassName: nginx
  rules:
    - host: "victorialogs.apatsev.org.ru"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vlc-victoria-logs-cluster-vlselect
                port: 
                  name: http

